### ISSUE TITLE
Bug. 

### ISSUE THREAD

**Issue by rokibot009** [Shock95x/AuctionHouse#100]
### Issue description
Write the issue description here

there is a bug. when I want to buy things from my friend 

versions:
* PocketMine-MP: 3.25.4
* Plugin version: 1.3.3

Link Video:
-https://drive.google.com/file/d/18tX7iDa9b4b6K0efRpVXOp2PNkwCmdaE/view?usp=drivesdk

**Comment by Shock95x** [comment]
This shouldn't occur in the latest version if you have InvCrashFix
