### ISSUE TITLE
[PM4] Dupe bug

### ISSUE THREAD

**Issue by ipad54** [Shock95x/AuctionHouse#103]
### Issue description
Hi, i found a dupe

### Steps to reproduce the issue
1. On video

### OS and versions
* PocketMine-MP: 4.2.0
* Plugin version: 2.0.0-BETA 1 (https://github.com/Shock95x/AuctionHouse/commit/d6feda81dc7325ad06f18e490ce5f1f5d9599990)
* Server OS: Win

### Error/Crash log (If available)
https://www.youtube.com/watch?v=nwieQNKzY2k

**Comment by Shock95x** [comment]
Fixed
