### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by PSYCHO678** [Shock95x/AuctionHouse#106]
1.  Server crashing when buying from ah 
[15:58:31.927] [Server thread/CRITICAL]: TypeError: "implode(): Argument #2 ($array) must be of type ?array, string given" (EXCEPTION) in "plugins/AuctionHouse.phar/src/shock95x/auctionhouse/menu/admin/ManageListingMenu" at line 37
And im also not seeing player name and price on ah 
![image](https://user-images.githubusercontent.com/84683932/159958747-0ff31072-b1b7-4bda-a603-e49d7300d3c1.png)

**Comment by DevTIG3535** [comment]
> Die Platzhalter verwenden jetzt geschweifte Klammern, also sollte es anstelle von `%price%` `{PRICE}` sein. Stellen Sie sicher, dass Ihre Sprachdateien aktualisiert werden  ![ E3410182-24C6-43D7-89E4-4DAA6C066E53]


(https://user-images.githubusercontent.com/101284125/160229527-9a6a4734-1a42-4b96-aa17-1908c170f3a4.png)

Ich habe einen Artikel gekauft und habe einen schwarzen Bildschirm, aber der Artikel ist nicht

**Comment by PSYCHO678** [comment]
> The placeholders use braces now so instead of `%price%` it should be `{PRICE}`. Make sure your language files are updated

thanks
