### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by DevTIG3535** [Shock95x/AuctionHouse#108]
I bought an item and have a black screen but the item is not.
![EF10A9FE-EA9F-43AE-A2AF-7B4BBAEC6CA5](https://user-images.githubusercontent.com/101284125/160233701-6d2e3d76-da03-4256-a038-3503b8b552bb.png)

**Comment by Shock95x** [comment]
Do you have [InvCrashFix](https://poggit.pmmp.io/ci/Muqsit/InvCrashFix) installed? It should fix this issue

**Comment by DevTIG3535** [comment]
> Do you have [InvCrashFix](https://poggit.pmmp.io/ci/Muqsit/InvCrashFix) installed? It should fix this issue

Now it works. Thank you very much! :)
