### ISSUE TITLE
Bug in most recent build #8

### ISSUE THREAD

**Issue by TetroYT** [Shock95x/AuctionHouse#11]
![27F08C3F-BE0E-47D1-B631-4E60AFFAEBC5](https://user-images.githubusercontent.com/49662383/73272997-315c5780-41db-11ea-9f95-d8623f9d3847.png)

do any of the older builds work that i could use while this is being fixed?

**Comment by TheUtopianPlayz** [comment]
i get the same error when 1 of my players run the command
it works for most players but not for some
for me its just been players with spaces in there names

**Comment by Shock95x** [comment]
@TheUtopianPlayz @TetroYT  The error seems to be caused by players with a different language set other than English, I'm currently working on a fix.

**Comment by TheUtopianPlayz** [comment]
Just so u know ur English ymls are all different
The one the plugin generates is: en_US
The one listed as default in the config is: en-US
And the 1 in the errors that the plugin is calling for is:en-us
