### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by TetroYT** [Shock95x/AuctionHouse#15]
Thanks for the recent update fix it works now, you should try and get this into the releases part of poggit its the best public auction house plugin ive ever seen and would get so many 5 star reviews.

![ED9B7354-B3B2-4BEB-9654-B865E6166748](https://user-images.githubusercontent.com/49662383/73605344-0ab06f00-4595-11ea-89e0-00365fa9fd7c.png)

**Comment by Shock95x** [comment]
I'll release it on Poggit once there are no more errors, thanks.
