### ISSUE TITLE
issue with build 15

### ISSUE THREAD

**Issue by TheUtopianPlayz** [Shock95x/AuctionHouse#17]
after reboot u dont have the option to remove items u posted on the ah anymore, there still up and u still get the money but u cant remove them if u want to

**Comment by Shock95x** [comment]
Do the items show up in the listings and expired menu? You should be able to return your items by dragging them into your inventory from the expired menu

**Comment by TheUtopianPlayz** [comment]
U can't remove them from listings because they don't show up

**Comment by Shock95x** [comment]
Do they show in the main auction menu?

**Comment by TheUtopianPlayz** [comment]
yes but after reboot they dont show up in "/ah listings"

**Comment by Shock95x** [comment]
Have you noticed any errors in the console?

**Comment by Shock95x** [comment]
@TheUtopianPlayz I'm not able to replicate this issue and no one else seems to have it, if there are any errors in the console make sure to include them
