### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ipad54** [Shock95x/AuctionHouse#28]
If you reboot the server, then sometimes the plugin may throw an error. If you reboot again, then everything is fine

Error: Fatal error: Uncaught TypeError: SQlite3::__construct() expects parametr 1 to be a valid path, null given in
/srv/data/plugins/AuctionHouse/src/shock95x/auctionhouse/libs/poggit/libasynql/sqlite/SQlite3Thread on line 68

**Comment by Shock95x** [comment]
Are you using the /reload command?

**Comment by ipad54** [comment]
@Shock95x No

**Comment by Shock95x** [comment]
@ipad54 Try the latest release (v1.1.0)

**Comment by Shock95x** [comment]
@ipad54 Are you still getting this error on v1.1.0?

**Comment by ipad54** [comment]
@Shock95x Yes, I get this error if I use sqlite database

**Comment by Shock95x** [comment]
@ipad54 Is that the full error log?

**Comment by Shock95x** [comment]
> @Shock95x, 
> Now I downloaded from poggit and everything started, that time too, but there was an error, now I do not observe it

_Originally posted by @ipad54 in https://github.com/Shock95x/AuctionHouse/issues/48#issuecomment-670956710_
