### ISSUE TITLE
Sudden Loading Error

### ISSUE THREAD

**Issue by CtrlAltTr0ll** [Shock95x/AuctionHouse#32]
plugin was working perfectly, then all of a sudden has stopped loading and throws this error:

> 01.06 17:02:24 [Server] Server thread/INFO Enabling AuctionHouse v1.0.9
01.06 17:02:24 [Server] Server thread/CRITICAL TypeError: "fclose() expects parameter 1 to be resource, null given" (EXCEPTION) in "plugins/AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/generic/GenericStatementFileParser" at line 88
01.06 17:02:24 [Server] Server thread/DEBUG #0 plugins/AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/generic/GenericStatementFileParser(88): fclose(NULL )
01.06 17:02:24 [Server] Server thread/DEBUG #1 plugins/AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/base/DataConnectorImpl(89): shock95x\auctionhouse\libs\poggit\libasynql\generic\GenericStatementFileParser->parse()
01.06 17:02:24 [Server] Server thread/DEBUG #2 plugins/AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/libasynql(146): shock95x\auctionhouse\libs\poggit\libasynql\base\DataConnectorImpl->loadQueryFile(NULL )
01.06 17:02:24 [Server] Server thread/DEBUG #3 plugins/AuctionHouse (1).phar/src/shock95x/auctionhouse/database/Database(44): shock95x\auctionhouse\libs\poggit\libasynql\libasynql::create(object shock95x\auctionhouse\AuctionHouse, array[4], array[1])
01.06 17:02:24 [Server] Server thread/DEBUG #4 plugins/AuctionHouse (1).phar/src/shock95x/auctionhouse/AuctionHouse(75): shock95x\auctionhouse\database\Database->connect()
01.06 17:02:24 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/PluginBase(115): shock95x\auctionhouse\AuctionHouse->onEnable()
01.06 17:02:24 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/PluginManager(541): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
01.06 17:02:24 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1783): pocketmine\plugin\PluginManager->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
01.06 17:02:24 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1769): pocketmine\Server->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
01.06 17:02:24 [Server] Server thread/DEBUG #9 src/pocketmine/Server(1582): pocketmine\Server->enablePlugins(integer 1)
01.06 17:02:24 [Server] Server thread/DEBUG #10 src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
01.06 17:02:24 [Server] Server thread/DEBUG #11 src/pocketmine/PocketMine(295): pocketmine\server()
01.06 17:02:24 [Server] Server thread/DEBUG #12 (11): require(string[108] phar:///PMMP-Latest-Stable.phar/s)
01.06 17:02:24 [Server] Server thread/DEBUG Previous: TypeError: "fgets() expects parameter 1 to be resource, null given" (EXCEPTION) in "plugins/AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/generic/GenericStatementFileParser" at line 81
01.06 17:02:24 [Server] Server thread/DEBUG #0 plugins/AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/generic/GenericStatementFileParser(81): fgets(NULL )
01.06 17:02:24 [Server] Server thread/DEBUG #1 plugins/AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/base/DataConnectorImpl(89): shock95x\auctionhouse\libs\poggit\libasynql\generic\GenericStatementFileParser->parse()
01.06 17:02:24 [Server] Server thread/DEBUG #2 plugins/AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/libasynql(146): shock95x\auctionhouse\libs\poggit\libasynql\base\DataConnectorImpl->loadQueryFile(NULL )
01.06 17:02:24 [Server] Server thread/DEBUG #3 plugins/AuctionHouse (1).phar/src/shock95x/auctionhouse/database/Database(44): shock95x\auctionhouse\libs\poggit\libasynql\libasynql::create(object shock95x\auctionhouse\AuctionHouse, array[4], array[1])
01.06 17:02:24 [Server] Server thread/DEBUG #4 plugins/AuctionHouse (1).phar/src/shock95x/auctionhouse/AuctionHouse(75): shock95x\auctionhouse\database\Database->connect()
01.06 17:02:24 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/PluginBase(115): shock95x\auctionhouse\AuctionHouse->onEnable()
01.06 17:02:24 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/PluginManager(541): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
01.06 17:02:24 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1783): pocketmine\plugin\PluginManager->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
01.06 17:02:24 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1769): pocketmine\Server->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
01.06 17:02:24 [Server] Server thread/DEBUG #9 src/pocketmine/Server(1582): pocketmine\Server->enablePlugins(integer 1)
01.06 17:02:24 [Server] Server thread/DEBUG #10 src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
01.06 17:02:24 [Server] Server thread/DEBUG #11 src/pocketmine/PocketMine(295): pocketmine\server()
01.06 17:02:24 [Server] Server thread/DEBUG #12 (11): require(string[108] phar:///PMMP-Latest-Stable.phar/s)
01.06 17:02:24 [Server] Server thread/INFO Disabling AuctionHouse v1.0.9
01.06 17:02:24 [Server] Server thread/CRITICAL Error: "Call to a member function save() on null" (EXCEPTION) in "plugins/AuctionHouse (1).phar/src/shock95x/auctionhouse/AuctionHouse" at line 93
01.06 17:02:24 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/PluginBase(117): shock95x\auctionhouse\AuctionHouse->onDisable()
01.06 17:02:24 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/PluginManager(628): pocketmine\plugin\PluginBase->setEnabled(boolean )
01.06 17:02:24 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginManager(548): pocketmine\plugin\PluginManager->disablePlugin(object shock95x\auctionhouse\AuctionHouse)
01.06 17:02:24 [Server] Server thread/DEBUG #3 src/pocketmine/Server(1783): pocketmine\plugin\PluginManager->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
01.06 17:02:24 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1769): pocketmine\Server->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
01.06 17:02:24 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1582): pocketmine\Server->enablePlugins(integer 1)
01.06 17:02:24 [Server] Server thread/DEBUG #6 src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
01.06 17:02:24 [Server] Server thread/DEBUG #7 src/pocketmine/PocketMine(295): pocketmine\server()
01.06 17:02:24 [Server] Server thread/DEBUG #8 (11): require(string[108] phar:///PMMP-Latest-Stable.phar/s)

**Comment by ElectroGamesYT** [comment]
Same

**Comment by xKurt21** [comment]
same

**Comment by Shock95x** [comment]
Provide your config file

**Comment by Shock95x** [comment]
Fixed in v1.1.0.
