### ISSUE TITLE
It's not loading in anymore

### ISSUE THREAD

**Issue by KareemDoesMc** [Shock95x/AuctionHouse#33]
05.06 00:26:17 [Server] Server thread/CRITICAL TypeError: "fclose() expects parameter 1 to be resource, null given" (EXCEPTION) in "plugins/1587002690262_AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/generic/GenericStatementFileParser" at line 88
05.06 00:26:17 [Server] Server thread/DEBUG #0 plugins/1587002690262_AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/generic/GenericStatementFileParser(88): fclose(NULL )
05.06 00:26:17 [Server] Server thread/DEBUG #1 plugins/1587002690262_AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/base/DataConnectorImpl(89): shock95x\auctionhouse\libs\poggit\libasynql\generic\GenericStatementFileParser->parse()
05.06 00:26:17 [Server] Server thread/DEBUG #2 plugins/1587002690262_AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/libasynql(146): shock95x\auctionhouse\libs\poggit\libasynql\base\DataConnectorImpl->loadQueryFile(NULL )
05.06 00:26:17 [Server] Server thread/DEBUG #3 plugins/1587002690262_AuctionHouse (1).phar/src/shock95x/auctionhouse/database/Database(44): shock95x\auctionhouse\libs\poggit\libasynql\libasynql::create(object shock95x\auctionhouse\AuctionHouse, array[4], array[1])
05.06 00:26:17 [Server] Server thread/DEBUG #4 plugins/1587002690262_AuctionHouse (1).phar/src/shock95x/auctionhouse/AuctionHouse(75): shock95x\auctionhouse\database\Database->connect()
05.06 00:26:17 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/PluginBase(115): shock95x\auctionhouse\AuctionHouse->onEnable()
05.06 00:26:17 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/PluginManager(541): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
05.06 00:26:17 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1783): pocketmine\plugin\PluginManager->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
05.06 00:26:17 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1769): pocketmine\Server->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
05.06 00:26:17 [Server] Server thread/DEBUG #9 src/pocketmine/Server(1582): pocketmine\Server->enablePlugins(integer 1)
05.06 00:26:17 [Server] Server thread/DEBUG #10 src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
05.06 00:26:17 [Server] Server thread/DEBUG #11 src/pocketmine/PocketMine(295): pocketmine\server()
05.06 00:26:17 [Server] Server thread/DEBUG #12 (11): require(string[116] phar:///PMMP-1.14.60-Latest-Stabl)
05.06 00:26:17 [Server] Server thread/DEBUG Previous: TypeError: "fgets() expects parameter 1 to be resource, null given" (EXCEPTION) in "plugins/1587002690262_AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/generic/GenericStatementFileParser" at line 81
05.06 00:26:17 [Server] Server thread/DEBUG #0 plugins/1587002690262_AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/generic/GenericStatementFileParser(81): fgets(NULL )
05.06 00:26:17 [Server] Server thread/DEBUG #1 plugins/1587002690262_AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/base/DataConnectorImpl(89): shock95x\auctionhouse\libs\poggit\libasynql\generic\GenericStatementFileParser->parse()
05.06 00:26:17 [Server] Server thread/DEBUG #2 plugins/1587002690262_AuctionHouse (1).phar/src/shock95x/auctionhouse/libs/poggit/libasynql/libasynql(146): shock95x\auctionhouse\libs\poggit\libasynql\base\DataConnectorImpl->loadQueryFile(NULL )
05.06 00:26:17 [Server] Server thread/DEBUG #3 plugins/1587002690262_AuctionHouse (1).phar/src/shock95x/auctionhouse/database/Database(44): shock95x\auctionhouse\libs\poggit\libasynql\libasynql::create(object shock95x\auctionhouse\AuctionHouse, array[4], array[1])
05.06 00:26:17 [Server] Server thread/DEBUG #4 plugins/1587002690262_AuctionHouse (1).phar/src/shock95x/auctionhouse/AuctionHouse(75): shock95x\auctionhouse\database\Database->connect()
05.06 00:26:17 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/PluginBase(115): shock95x\auctionhouse\AuctionHouse->onEnable()
05.06 00:26:17 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/PluginManager(541): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
05.06 00:26:17 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1783): pocketmine\plugin\PluginManager->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
05.06 00:26:17 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1769): pocketmine\Server->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
05.06 00:26:17 [Server] Server thread/DEBUG #9 src/pocketmine/Server(1582): pocketmine\Server->enablePlugins(integer 1)
05.06 00:26:17 [Server] Server thread/DEBUG #10 src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
05.06 00:26:17 [Server] Server thread/DEBUG #11 src/pocketmine/PocketMine(295): pocketmine\server()
05.06 00:26:17 [Server] Server thread/DEBUG #12 (11): require(string[116] phar:///PMMP-1.14.60-Latest-Stabl)
05.06 00:26:17 [Server] Server thread/INFO Disabling AuctionHouse v1.0.9
05.06 00:26:17 [Server] Server thread/CRITICAL Error: "Call to a member function save() on null" (EXCEPTION) in "plugins/1587002690262_AuctionHouse (1).phar/src/shock95x/auctionhouse/AuctionHouse" at line 93
05.06 00:26:17 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/PluginBase(117): shock95x\auctionhouse\AuctionHouse->onDisable()
05.06 00:26:17 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/PluginManager(628): pocketmine\plugin\PluginBase->setEnabled(boolean )
05.06 00:26:17 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginManager(548): pocketmine\plugin\PluginManager->disablePlugin(object shock95x\auctionhouse\AuctionHouse)
05.06 00:26:17 [Server] Server thread/DEBUG #3 src/pocketmine/Server(1783): pocketmine\plugin\PluginManager->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
05.06 00:26:17 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1769): pocketmine\Server->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
05.06 00:26:17 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1582): pocketmine\Server->enablePlugins(integer 1)
05.06 00:26:17 [Server] Server thread/DEBUG #6 src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
05.06 00:26:17 [Server] Server thread/DEBUG #7 src/pocketmine/PocketMine(295): pocketmine\server()
05.06 00:26:17 [Server] Server thread/DEBUG #8 (11): require(string[116] phar:///PMMP-1.14.60-Latest-Stabl)

**Comment by Shock95x** [comment]
Fixed in v1.1.0.

**Comment by KareemDoezMc** [comment]
Is it released on poggit?

**Comment by Shock95x** [comment]
It's been submitted but you can download it from the releases tab right now

**Comment by KareemDoezMc** [comment]
Ok thank you
