### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RustlingBrick86** [Shock95x/AuctionHouse#34]
I think u need to update it to the new version cause it shows a huge error in console now

**Comment by Shock95x** [comment]
Try the latest version

**Comment by Shock95x** [comment]
@RustlingBrick86 Paste the error log and plugin version.

**Comment by Shock95x** [comment]
@RustlingBrick86 Is this happening on the latest version?

**Comment by Shock95x** [comment]
Messaged him on Discord, told him to update the plugin and now it's fine.
