### ISSUE TITLE
 Bug by starting from the Server

### ISSUE THREAD

**Issue by Shipyde** [Shock95x/AuctionHouse#35]
[Server thread/CRITICAL]: TypeError: "fclose() expects parameter 1 to be resource, null given" (EXCEPTION) in "plugins/AuctionHouse.phar/src/shock95x/auctionhouse/libs/poggit/libasynql/generic/GenericStatementFileParser" at line 88
[Server thread/DEBUG]: #0 plugins/AuctionHouse.phar/src/shock95x/auctionhouse/libs/poggit/libasynql/generic/GenericStatementFileParser(88): fclose(NULL )
[Server thread/DEBUG]: #1 plugins/AuctionHouse.phar/src/shock95x/auctionhouse/libs/poggit/libasynql/base/DataConnectorImpl(89): shock95x\auctionhouse\libs\poggit\libasynql\generic\GenericStatementFileParser->parse()
[Server thread/DEBUG]: #2 plugins/AuctionHouse.phar/src/shock95x/auctionhouse/libs/poggit/libasynql/libasynql(146): shock95x\auctionhouse\libs\poggit\libasynql\base\DataConnectorImpl->loadQueryFile(NULL )
[Server thread/DEBUG]: #3 plugins/AuctionHouse.phar/src/shock95x/auctionhouse/database/Database(44): shock95x\auctionhouse\libs\poggit\libasynql\libasynql::create(object shock95x\auctionhouse\AuctionHouse, array[4], array[1])
[Server thread/DEBUG]: #4 plugins/AuctionHouse.phar/src/shock95x/auctionhouse/AuctionHouse(75): shock95x\auctionhouse\database\Database->connect()
[Server thread/DEBUG]: #5 src/pocketmine/plugin/PluginBase(116): shock95x\auctionhouse\AuctionHouse->onEnable()
[Server thread/DEBUG]: #6 src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
[Server thread/DEBUG]: #7 src/pocketmine/Server(1784): pocketmine\plugin\PluginManager->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
[Server thread/DEBUG]: #8 src/pocketmine/Server(1770): pocketmine\Server->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
[Server thread/DEBUG]: #9 src/pocketmine/Server(1583): pocketmine\Server->enablePlugins(integer 1)
[Server thread/DEBUG]: #10 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[23] /home/shipy/MP_Network/, string[31] /home/shipy/MP_Network/plugins/)
[Server thread/DEBUG]: #11 src/pocketmine/PocketMine(296): pocketmine\server()
[Server thread/DEBUG]: #12 (11): require(string[78] phar:///home/shipy/MP_Network/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
[Server thread/DEBUG]: Previous: TypeError: "fgets() expects parameter 1 to be resource, null given" (EXCEPTION) in "plugins/AuctionHouse.phar/src/shock95x/auctionhouse/libs/poggit/libasynql/generic/GenericStatementFileParser" at line 81
[Server thread/DEBUG]:   #0 plugins/AuctionHouse.phar/src/shock95x/auctionhouse/libs/poggit/libasynql/generic/GenericStatementFileParser(81): fgets(NULL )
[Server thread/DEBUG]:   #1 plugins/AuctionHouse.phar/src/shock95x/auctionhouse/libs/poggit/libasynql/base/DataConnectorImpl(89): shock95x\auctionhouse\libs\poggit\libasynql\generic\GenericStatementFileParser->parse()
[Server thread/DEBUG]:   #2 plugins/AuctionHouse.phar/src/shock95x/auctionhouse/libs/poggit/libasynql/libasynql(146): shock95x\auctionhouse\libs\poggit\libasynql\base\DataConnectorImpl->loadQueryFile(NULL )
[Server thread/DEBUG]:   #3 plugins/AuctionHouse.phar/src/shock95x/auctionhouse/database/Database(44): shock95x\auctionhouse\libs\poggit\libasynql\libasynql::create(object shock95x\auctionhouse\AuctionHouse, array[4], array[1])
[Server thread/DEBUG]:   #4 plugins/AuctionHouse.phar/src/shock95x/auctionhouse/AuctionHouse(75): shock95x\auctionhouse\database\Database->connect()
[Server thread/DEBUG]:   #5 src/pocketmine/plugin/PluginBase(116): shock95x\auctionhouse\AuctionHouse->onEnable()
[Server thread/DEBUG]:   #6 src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
[Server thread/DEBUG]:   #7 src/pocketmine/Server(1784): pocketmine\plugin\PluginManager->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
[Server thread/DEBUG]:   #8 src/pocketmine/Server(1770): pocketmine\Server->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
[Server thread/DEBUG]:   #9 src/pocketmine/Server(1583): pocketmine\Server->enablePlugins(integer 1)
[Server thread/DEBUG]:   #10 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[23] /home/shipy/MP_Network/, string[31] /home/shipy/MP_Network/plugins/)
[Server thread/DEBUG]:   #11 src/pocketmine/PocketMine(296): pocketmine\server()
[Server thread/DEBUG]:   #12 (11): require(string[78] phar:///home/shipy/MP_Network/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
[Server thread/INFO]: Deaktiviere AuctionHouse v1.0.9
[Server thread/CRITICAL]: Error: "Call to a member function save() on null" (EXCEPTION) in "plugins/AuctionHouse.phar/src/shock95x/auctionhouse/AuctionHouse" at line 93
[Server thread/DEBUG]: #0 src/pocketmine/plugin/PluginBase(118): shock95x\auctionhouse\AuctionHouse->onDisable()
[Server thread/DEBUG]: #1 src/pocketmine/plugin/PluginManager(639): pocketmine\plugin\PluginBase->setEnabled(boolean )
[Server thread/DEBUG]: #2 src/pocketmine/plugin/PluginManager(559): pocketmine\plugin\PluginManager->disablePlugin(object shock95x\auctionhouse\AuctionHouse)
[Server thread/DEBUG]: #3 src/pocketmine/Server(1784): pocketmine\plugin\PluginManager->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
[Server thread/DEBUG]: #4 src/pocketmine/Server(1770): pocketmine\Server->enablePlugin(object shock95x\auctionhouse\AuctionHouse)
[Server thread/DEBUG]: #5 src/pocketmine/Server(1583): pocketmine\Server->enablePlugins(integer 1)
[Server thread/DEBUG]: #6 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[23] /home/shipy/MP_Network/, string[31] /home/shipy/MP_Network/plugins/)
[Server thread/DEBUG]: #7 src/pocketmine/PocketMine(296): pocketmine\server()
[Server thread/DEBUG]: #8 (11): require(string[78] phar:///home/shipy/MP_Network/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by Shock95x** [comment]
Fixed in latest release
