### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ZenZenXDz** [Shock95x/AuctionHouse#36]
When I buy something at the AH the whole server crash.

**Comment by Shock95x** [comment]
Provide the crash dump here

**Comment by Shock95x** [comment]
@ZenZenXDz I wasn't able to reproduce this, are you using v1.1.0?

**Comment by Nagol12344** [comment]
it's confirmed

**Comment by Shock95x** [comment]
@Nagol12344 This isn't related to #38 if that's what you're talking about

**Comment by Nagol12344** [comment]
it is

**Comment by Shock95x** [comment]
Nope, if it was then only the client would crash. He said that the whole server crashed.

**Comment by Shock95x** [comment]
Closing due to no additional information
