### ISSUE TITLE
Reload Issue

### ISSUE THREAD

**Issue by JustJamezX** [Shock95x/AuctionHouse#41]
### Issue/Suggestion
So, every time I reload my server, /ah won't work. But if I restart my server, it'll work again. I've tried doing "/ah update" but it wont work. I'm on Pocketmine version 3.14.0 and using AuctionHouse version 1.1.1.

If you're wondering, I reload my server in order to get TopVoter to work.

**Comment by Shock95x** [comment]
Using /reload is not recommended, it’s supposedly being removed from PocketMine in the future.
