### ISSUE TITLE
Lores

### ISSUE THREAD

**Issue by rjworks** [Shock95x/AuctionHouse#43]
Lores are not shown in ah lists why not?

**Comment by Shock95x** [comment]
I'll add this as an option in a future release, item enchants should show though.

**Comment by rjworks** [comment]
> I'll add this as an option in a future release, item enchants should show though.

Custom enchants don't

**Comment by rjworks** [comment]
is the lore stored in nbt? maybe I can make pull req

**Comment by Shock95x** [comment]
Added in v1.2.0 (Currently a pre-release build)
https://github.com/Shock95x/AuctionHouse/releases/tag/1.2.0

**Comment by rjworks** [comment]
> Added in v1.2.0 (Currently a pre-release build)
> https://github.com/Shock95x/AuctionHouse/releases/tag/1.2.0

Legendary bro. Much love
