### ISSUE TITLE
high pct tick

### ISSUE THREAD

**Issue by rjworks** [Shock95x/AuctionHouse#47]
```
AuctionHouse v1.2.0-PRERELEASETotal: 1.782 s Pct: 0.12%
   Pct Total	Pct Tick	   Total	      Avg	 PerTick	     Count		Event
       0.04%	   0.04%	  0.63 s	     0.02 ms	  26	     809.5k	    shock95x\auctionhouse\libs\muqsit\invmenu\InvMenuEventHandler::onDataPacketReceive(DataPacketReceiveEvent)
       0.04%	 246.24%	  0.62 s	   123.12 ms	 0.0	       0.0k	    Task: shock95x\auctionhouse\task\ListingExpireTask(interval 6000)
       0.03%	   0.03%	  0.50 s	     0.02 ms	  25	     754.4k	    shock95x\auctionhouse\libs\CortexPE\Commando\PacketHooker::onPacketSend(DataPacketSendEvent)
       0.00%	   0.16%	  0.04 s	     0.08 ms	 0.0	       0.5k	    shock95x\auctionhouse\libs\muqsit\invmenu\InvMenuEventHandler::onInventoryTransaction(InventoryTransactionEvent)
       0.00%	   0.12%	  0.00 s	     0.06 ms	 0.0	       0.0k	    shock95x\auctionhouse\libs\muqsit\invmenu\InvMenuEventHandler::onPlayerJoin(PlayerJoinEvent)
       0.00%	   0.00%	  0.00 s	     0.00 ms	 0.0	       0.2k	    shock95x\auctionhouse\EventListener::onInventoryClose(InventoryCloseEvent)
       0.00%	   0.47%	  0.00 s	     0.24 ms	 0.0	       0.0k	    Task: shock95x\auctionhouse\task\MenuDelayTask(Single)
       0.00%	   0.01%	  0.00 s	     0.00 ms	 0.0	       0.0k	    shock95x\auctionhouse\libs\muqsit\invmenu\InvMenuEventHandler::onPlayerQuit(PlayerQuitEvent)
```

**Comment by rjworks** [comment]
the interval for this task is currently 5 mins. will anything break if i change it to 50 mins?

**Comment by Shock95x** [comment]
If you're confident that the server won't crash anytime then sure, but I already made optimizations and might push them soon

**Comment by rjworks** [comment]
im not confident 

can u make push that

**Comment by Shock95x** [comment]
I'm waiting for recursive inventories get fixed in InvMenu, until then I could use a delayed task to send menus as a workaround but it might not work all the time so I'm not sure.

**Comment by Shock95x** [comment]
I currently have a workaround that seems to work, if it doesn't break and everything else works fine I'll push it today

**Comment by rjworks** [comment]
does it break

**Comment by Shock95x** [comment]
Everything seems to be fine, I pushed a release an hour ago

**Comment by rjworks** [comment]
should i use that
i current have it the task every 55mins

**Comment by Shock95x** [comment]
I made optimizations in other areas besides the task so yeah

**Comment by rjworks** [comment]
oh ok will it no longer be 200+% pct tick then

**Comment by Shock95x** [comment]
The timings seemed to be good when I tested it, you can try it and check the results just to make sure

**Comment by rjworks** [comment]
why when i download 1.2 branch i get something else
something else not what i see in the 1.2 page.

**Comment by rjworks** [comment]
there is also no commando in virions:.

**Comment by Shock95x** [comment]
Are you downloading from the releases tab?

**Comment by rjworks** [comment]
ok that fixed it thanks a lot good job keep it up

**Comment by rjworks** [comment]
the pct tick improved a lot what did u do?

**Comment by Shock95x** [comment]
thanks, you can look at the description and changes here: https://github.com/Shock95x/AuctionHouse/commit/ae18be6df964b0769fcf1c20a2d3f3ed580c1fb1

I pretty much went over the plugin and checked everything I was able to optimize

**Comment by rjworks** [comment]
`- DB is now updated when a listing is created or expired`
is this not resource extensive?

**Comment by rjworks** [comment]
if not, i think i want to do that for my plugin too to save stats when the player leaves instead of all player at once every other time.

**Comment by Shock95x** [comment]
> `- DB is now updated when a listing is created or expired`
> is this not resource extensive?

Not necessarily since I don't think listings would be created that often and the DB lib is async too, it would actually be better in case of a fatal server crash

**Comment by rjworks** [comment]
> > `- DB is now updated when a listing is created or expired`
> > is this not resource extensive?
> 
> Not necessarily since I don't think listings would be created that often and the DB lib is async too, it would actually be better in case of a fatal server crash

everything in libasynql is async right including update

**Comment by Shock95x** [comment]
> > > `- DB is now updated when a listing is created or expired`
> > > is this not resource extensive?
> > 
> > 
> > Not necessarily since I don't think listings would be created that often and the DB lib is async too, it would actually be better in case of a fatal server crash
> 
> everything in libasynql is async right including update

yes

**Comment by rjworks** [comment]
> > > > `- DB is now updated when a listing is created or expired`
> > > > is this not resource extensive?
> > > 
> > > 
> > > Not necessarily since I don't think listings would be created that often and the DB lib is async too, it would actually be better in case of a fatal server crash
> > 
> > 
> > everything in libasynql is async right including update
> 
> yes

do you think it would be a bad idea to save stats ;ike kills and deaths to SQLite every time the player leaves?
