### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by rjworks** [Shock95x/AuctionHouse#51]
### Issue description
Write the issue description here
internal server error https://mcpaste.io/1582df78eb91f097
### Steps to reproduce the issue
``Was buying something from auction house, clicked on the item to start the purchase, it didn’t go through and just exited the ah panel. I do /ah again to try making the purchase and I got internal server error``

### OS and versions
* PocketMine-MP:3.15.0
* Plugin version: 1.2.0
* Server OS:ubuntu 18

### Error/Crash log (If available)

```
 https://mcpaste.io/1582df78eb91f097
```

**Comment by rjworks** [comment]
When i download the src it gives me the old task which was laggy

**Comment by Shock95x** [comment]
You might've downloaded it from the master branch before I merged it, download it again if it still doesn't work download the phar and extract it here: https://pmt.nathfreder.dev/extract

**Comment by Shock95x** [comment]
This seems to happen when you close the purchase confirm menu right away and open the AH menu again

**Comment by Shock95x** [comment]
Should be fixed in latest release
