### ISSUE TITLE
Update"Class 'JackMD\UpdateNotifier\UpdateNotifier' not found"

### ISSUE THREAD

**Issue by spiderant9** [Shock95x/AuctionHouse#54]
installed the new version and it seems to be missing update notifier

06.09 06:37:12 [Server] Server thread/INFO Loading AuctionHouse v1.2.2
06.09 06:37:12 [Server] Server thread/CRITICAL Error: "Class 'JackMD\UpdateNotifier\UpdateNotifier' not found" (EXCEPTION) in "plugins/AuctionHouse-master/src/shock95x/auctionhouse/AuctionHouse" at line 28
06.09 06:37:12 [Server] Server thread/CRITICAL #0 src/pocketmine/plugin/PluginManager(182): shock95x\auctionhouse\AuctionHouse->onLoad()
06.09 06:37:12 [Server] Server thread/CRITICAL #1 src/pocketmine/plugin/PluginManager(346): pocketmine\plugin\PluginManager->loadPlugin(string[75] /plugins/AuctionHouse-master, array[1])
06.09 06:37:12 [Server] Server thread/CRITICAL #2 plugins/PocketMine-DevTools (1).phar/src/DevTools/DevTools(49): pocketmine\plugin\PluginManager->loadPlugins(string[56] /plugins/, array[1])
06.09 06:37:12 [Server] Server thread/CRITICAL #3 src/pocketmine/plugin/PluginBase(116): DevTools\DevTools->onEnable()
06.09 06:37:12 [Server] Server thread/CRITICAL #4 src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
06.09 06:37:12 [Server] Server thread/CRITICAL #5 src/pocketmine/Server(1787): pocketmine\plugin\PluginManager->enablePlugin(object DevTools\DevTools)
06.09 06:37:12 [Server] Server thread/CRITICAL #6 src/pocketmine/Server(1773): pocketmine\Server->enablePlugin(object DevTools\DevTools)
06.09 06:37:12 [Server] Server thread/CRITICAL #7 src/pocketmine/Server(1532): pocketmine\Server->enablePlugins(integer 0)
06.09 06:37:12 [Server] Server thread/CRITICAL #8 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
06.09 06:37:12 [Server] Server thread/CRITICAL #9 src/pocketmine/PocketMine(304): pocketmine\server()
06.09 06:37:12 [Server] Server thread/CRITICAL #10 (11): require(string[108] phar:///PMMP-Latest-Stable.phar/s)
06.09 06:37:12 [Server] Server thread/CRITICAL Could not load plugin 'AuctionHouse'

**Comment by Shock95x** [comment]
If you're running the plugin from source make sure you have the virions installed
