### ISSUE TITLE
Internal Error when a player tap to buy an item sold by another player.

### ISSUE THREAD

**Issue by Jimminou** [Shock95x/AuctionHouse#55]
### Issue description
I think that your plugin is all good but one and only thing to report is when a player tap to buy an item sold by another player, it's crashing and closing the app. Same if the own player want to buy is own item (yes for the test i does this and it's the same). In fact, buying item is crashing.

### Steps to reproduce the issue
1. Player1 sell an item
2. Player2 try to tap to pay the item

### OS and versions
* PocketMine-MP: 3.15.0 and 3.16.0
* Plugin version: ALL VERSIONS

### Error/Crash log (If available)
NO LOG
```

```

**Comment by Shock95x** [comment]
I can't do much without a crash log.

**Comment by Shock95x** [comment]
Also make sure you have the InvCrashFix installed

**Comment by Jimminou** [comment]
There are no logs, that's the problem. It's says only "player has left the game" but I never tryied why InvCrashFix effectivly, i'm gonna try it right now, i 'm back quickly

**Comment by Jimminou** [comment]
Ok... Thank you my friend, that's working. Maybe that was wrotten on your description but I never seen that I have to get InvCrashFix plugin, maybe write it as bold ;) thanks again

**Comment by Shock95x** [comment]
Yeah no problem, I put a warning in the plugin if it doesn't detect InvCrashFix but I'll try to make it more clear next time!
