### ISSUE TITLE
InvCrashfix bug

### ISSUE THREAD

**Issue by Arata-Tempest** [Shock95x/AuctionHouse#60]
I am using version 1.2.4 and it does not work and in my server logs it says it needs InvCrashfix but I can not use this plugin because I use Aternos website and it only supports piggt plugins and invcrashfix is not from poggit Can you please solve this problem?...
![Screenshot_2020-09-29-01-07-35-1](https://user-images.githubusercontent.com/71513892/94856218-8290ab00-043c-11eb-99e3-fbeda6c706d9.png)

**Comment by Shock95x** [comment]
Unfortunately I can't do anything about that, you might want to contact the server provider and ask them to add it instead
