### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Arata-Tempest** [Shock95x/AuctionHouse#62]
Why does Auctionhouse need InvCrashFix? Can't you do something you don't need?
![Screenshot_2020-10-05-18-50-38-1](https://user-images.githubusercontent.com/71513892/95098671-d8ff3180-073b-11eb-81cd-c0ec436159aa.png)

Every time I try to buy an item from Auction House, it crashes!!!

**Comment by Arata-Tempest** [comment]
The server provider cannot override InvCrashfix and says it is not a security plugin!

**Comment by Shock95x** [comment]
If the server provider won't add it there's nothing I can do about it, sorry
