### ISSUE TITLE
Buy Item

### ISSUE THREAD

**Issue by Arata-Tempest** [Shock95x/AuctionHouse#65]
### Issue description
Write the issue description here

### Steps to reproduce the issue
1. ... {{I throw myself out of the game when I want to buy an item}}
2. ...

### OS and versions
* PocketMine-MP: 3.15.2
* Plugin version: 1.2.5
* Server OS:

### Error/Crash log (If available)

```
{{It does not give any errors and the server is still working}}
```

**Comment by djmaisen** [comment]
I have the same problem

**Comment by Shock95x** [comment]
Make sure you have InvCrashFix installed.
