### ISSUE TITLE
bjr I have a problem I would like to change the language to french but its bugged the plugin if you could help me it would make me happy

### ISSUE THREAD

**Issue by willtom6666** [Shock95x/AuctionHouse#66]
### Issue description
Write the issue description here

### Steps to reproduce the issue
1. ...
2. ...

### OS and versions
* PocketMine-MP:
* Plugin version: 
* Server OS:

### Error/Crash log (If available)

```

```

**Comment by Shock95x** [comment]
@willtom6666 French isn't a supported language at the moment, you can make a copy of the en_US file and translate it yourself if you would like to
