### ISSUE TITLE
but its done crash my server when I create a new one and its not located on language

### ISSUE THREAD

**Issue by willtom6666** [Shock95x/AuctionHouse#67]
### Issue description
Write the issue description here

### Steps to reproduce the issue
1. ...
2. ...

### OS and versions
* PocketMine-MP:
* Plugin version: 
* Server OS:

### Error/Crash log (If available)

```

```

**Comment by willtom6666** [comment]
plz put this language because I already tested and we did not succeed

**Comment by Shock95x** [comment]
@willtom6666 Message me on Discord: Shock95#7212
