### ISSUE TITLE
Auctioning an item with custom name and no enchant will transfer into normal item

### ISSUE THREAD

**Issue by Adam1609** [Shock95x/AuctionHouse#70]
### Issue description
When executing /ah sell while holding an item with custom name, the item showing the auction menu will be turning into normal, while an item like armor, weapon with enchant seems to be normal

### Steps to reproduce the issue
1. Execute /ah sell while holding item with custom name, no enchants
2. Open /ah
3. /ah will show item with no custom name

### OS and versions
* PocketMine-MP: 3.17.0
* Plugin version: 1.2.5
* Server OS: Windows 10 Ultimate 64-bit

### Error/Crash log (If available)

```

```

**Comment by Shock95x** [comment]
Unable to produce, if you could send screenshots or a video that would be helpful

**Comment by Shock95x** [comment]
Closing due to no response.
