### ISSUE TITLE
Saving data issue

### ISSUE THREAD

**Issue by austv** [Shock95x/AuctionHouse#71]
### Issue description
Server crashing frequently. In the logs is possible to see the auction house problem with the storage method (sqlite).

### Steps to reproduce the issue
1. Someone auction a item in /ah.

### OS and versions
* Tuinity 1.15.2
* AH 2.1.12.

### Error/Crash log (If available)
https://pastebin.com/raw/MfXXGbeZ

**Comment by Shock95x** [comment]
I think you have the wrong repository, this plugin is only for PocketMine-MP (Minecraft Bedrock)

**Comment by austv** [comment]
Sorry about that.
