### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by RustlingBrick86** [Shock95x/AuctionHouse#81]
### Issue description
Write the issue description here

### Steps to reproduce the issue
1. Add the currrent version to a 1.17.10 server
2. Join and it kicks you instantly

### OS and versions
* PocketMine-MP:
* Plugin version: 
* Server OS:

### Error/Crash log (If available)

```

```

**Comment by Shock95x** [comment]
This doesn't seem to be an issue anymore, closing
