### ISSUE TITLE
If you need help understanding contact me on discord - ParadoxGamimg#3516

### ISSUE THREAD

**Issue by RustlingBrick86** [Shock95x/AuctionHouse#99]
**Write feature/suggestion here**
Make it so there can be multiple permissions made for instant auctionhouse.listing.12 or ah.listing.12 etc, Basically would allow server owners to make it so different ranks can ah different amounts of items. For instance the default amount could be 4 items and you could set a permission to a rank that allows them to ah 12 items.

**Additional context**

**Comment by Shock95x** [comment]
This can be done by using the permission `auctionhouse.limit.#`, this has been in the plugin for a while but hasn't been documented until recently.
